In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
plt.style.use("ggplot")
%matplotlib inline

In [2]:
# Load Dataset
df = pd.read_csv("data/Top Indian Places to Visit.csv")

In [3]:
df.head()

,Unnamed: 0,Zone,State,City,Name,Type,Establishment Year,time needed to visit in hrs,Google review rating,Entrance Fee in INR,Airport with 50km Radius,Weekly Off,Significance,DSLR Allowed,Number of google review in lakhs,Best Time to visit
0,0,Northern,Delhi,Delhi,India Gate,War Memorial,1921,0.5,4.6,0,Yes,NaN,Historical,Yes,2.60,Evening
1,1,Northern,Delhi,Delhi,Humayun's Tomb,Tomb,1572,2.0,4.5,30,Yes,NaN,Historical,Yes,0.40,Afternoon
2,2,Northern,Delhi,Delhi,Akshardham Temple,Temple,2005,5.0,4.6,60,Yes,NaN,Religious,No,0.40,Afternoon
3,3,Northern,Delhi,Delhi,Waste to Wonder Park,Theme Park,2019,2.0,4.1,50,Yes,Monday,Environmental,Yes,0.27,Evening
4,4,Northern,Delhi,Delhi,Jantar Mantar,Observatory,1724,2.0,4.2,15,Yes,NaN,Scientific,Yes,0.31,Morning

In [5]:
df.shape

(325, 16)

In [6]:
df.columns

Index(['Unnamed: 0', 'Zone', 'State', 'City', 'Name', 'Type',
       'Establishment Year', 'time needed to visit in hrs',
       'Google review rating', 'Entrance Fee in INR',
       'Airport with 50km Radius', 'Weekly Off', 'Significance',
       'DSLR Allowed', 'Number of google review in lakhs',
       'Best Time to visit'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 16 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Unnamed: 0                        325 non-null    int64
 1   Zone                              325 non-null    str
 2   State                             325 non-null    str
 3   City                              325 non-null    str
 4   Name                              325 non-null    str
 5   Type                              325 non-null    str
 6   Establishment Year                325 non-null    str
 7   time needed to visit in hrs       325 non-null    float64
 8   Google review rating              325 non-null    float64
 9   Entrance Fee in INR               325 non-null    int64
 10  Airport with 50km Radius          325 non-null    str
 11  Weekly Off                        32 non-null     str
 12  Significance                      325 non-null    str
 13  DSLR Allowed                      325 non-null    str
 14  Number of google review in lakhs  325 non-null    float64
 15  Best Time to visit                325 non-null    str
dtypes: float64(3), int64(2), str(11)
memory usage: 64.3 KB

In [8]:
df.isnull().sum()

Unnamed: 0                            0
Zone                                  0
State                                 0
City                                  0
Name                                  0
Type                                  0
Establishment Year                    0
time needed to visit in hrs           0
Google review rating                  0
Entrance Fee in INR                   0
Airport with 50km Radius              0
Weekly Off                          293
Significance                          0
DSLR Allowed                          0
Number of google review in lakhs      0
Best Time to visit                    0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.drop(columns=["Unnamed: 0"], inplace=True)

In [11]:
df.head()

,Zone,State,City,Name,Type,Establishment Year,time needed to visit in hrs,Google review rating,Entrance Fee in INR,Airport with 50km Radius,Weekly Off,Significance,DSLR Allowed,Number of google review in lakhs,Best Time to visit
0,Northern,Delhi,Delhi,India Gate,War Memorial,1921,0.5,4.6,0,Yes,NaN,Historical,Yes,2.60,Evening
1,Northern,Delhi,Delhi,Humayun's Tomb,Tomb,1572,2.0,4.5,30,Yes,NaN,Historical,Yes,0.40,Afternoon
2,Northern,Delhi,Delhi,Akshardham Temple,Temple,2005,5.0,4.6,60,Yes,NaN,Religious,No,0.40,Afternoon
3,Northern,Delhi,Delhi,Waste to Wonder Park,Theme Park,2019,2.0,4.1,50,Yes,Monday,Environmental,Yes,0.27,Evening
4,Northern,Delhi,Delhi,Jantar Mantar,Observatory,1724,2.0,4.2,15,Yes,NaN,Scientific,Yes,0.31,Morning

In [12]:
df["Weekly Off"] = df["Weekly Off"].fillna("Open Daily")

In [13]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.dtypes

Zone                                    str
State                                   str
City                                    str
Name                                    str
Type                                    str
Establishment Year                      str
time needed to visit in hrs         float64
Google review rating                float64
Entrance Fee in INR                   int64
Airport with 50km Radius                str
Weekly Off                              str
Significance                            str
DSLR Allowed                            str
Number of google review in lakhs    float64
Best Time to visit                      str
dtype: object

In [16]:
df["Google review rating"] = pd.to_numeric(df["Google review rating"], errors="coerce")
df["Entrance Fee in INR"] = pd.to_numeric(df["Entrance Fee in INR"], errors="coerce")
df["time needed to visit in hrs"] = pd.to_numeric(df["time needed to visit in hrs"], errors="coerce")

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 15 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Zone                              325 non-null    str
 1   State                             325 non-null    str
 2   City                              325 non-null    str
 3   Name                              325 non-null    str
 4   Type                              325 non-null    str
 5   Establishment Year                325 non-null    str
 6   time needed to visit in hrs       325 non-null    float64
 7   Google review rating              325 non-null    float64
 8   Entrance Fee in INR               325 non-null    int64
 9   Airport with 50km Radius          325 non-null    str
 10  Weekly Off                        325 non-null    str
 11  Significance                      325 non-null    str
 12  DSLR Allowed                      325 non-null    str
 13  Number of google review in lakhs  325 non-null    float64
 14  Best Time to visit                325 non-null    str
dtypes: float64(3), int64(1), str(11)
memory usage: 64.6 KB

In [20]:
df.to_csv("data/cleaned_places.csv", index=False)